name: Bridge Actions

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Cache npm dependencies
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run linting
      - name: Run ESLint
        run: npm run lint

      # Run Prettier format check
      - name: Run Prettier check
        run: npm run prettier-check

      # Run tests with Jest
      # - name: Run tests
      #   run: npm run test

      # Run build for all apps
      - name: Build all apps
        run: npm run build